2023-05-17 19:50:02,654 - __main__ - INFO - /home/jeremy/Development/newsletters/data
2023-05-17 19:52:45,701 - __main__ - INFO - /home/jeremy/Development/newsletters/data
2023-11-01 14:33:52,997 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 112, in download_file
    return send_from_directory(directory='rota', filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
2023-11-01 14:34:25,267 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 112, in download_file
    return send_from_directory(directory='rota', filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
2023-11-01 14:36:17,614 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 113, in download_file
    return send_from_directory(rota_folder, filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
2023-11-01 14:36:34,344 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 113, in download_file
    return send_from_directory(rota_folder, filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
2023-11-01 14:38:20,784 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 113, in download_file
    return send_from_directory(rota_folder, filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
2023-11-01 14:38:43,040 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 113, in download_file
    return send_from_directory(rota_folder, filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
2023-11-01 14:39:05,032 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 113, in download_file
    return send_from_directory(rota_folder, filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
2023-11-01 14:39:13,184 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 113, in download_file
    return send_from_directory(rota_folder, filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
2023-11-01 14:39:53,790 - main - ERROR - Exception on /kingsrota [GET]
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jeremy/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jeremy/Documents/GitHub/newsletters/main.py", line 113, in download_file
    return send_from_directory(rota_folder, filename='kings.ics', as_attachment=True)
TypeError: send_from_directory() missing 1 required positional argument: 'path'
